version: '3.3'
services:
    db:
        build: ./DataBase
        restart: always
        ports:
            - '3306:3306'
        networks: 
            - db_auth
        volumes:
            #Criar o volume para pressistencia
            - my-db:/var/lib/mysql 
        cap_add:
            - SYS_NICE  # Correção do problema: "mbind: Operation not permitted"
    auth:
        depends_on:
            - db
        build: ./Authentication
        ports:
            - '3000:3000'
        expose: 
            - '3000'
        networks: 
            - db_auth
            - auth_http
    http:
        depends_on:
            - auth
        build: ./HTTP
        ports:
            - '4000:4000'
        expose: 
            - '4000'
        volumes:
            #Criar o volume para pressistencia
            - my-data-http:/server/data 
        networks: 
            - auth_http
volumes:
    my-db:
        driver: local
    my-data-http:
        driver: local
networks: 
    db_auth:
    auth_http: